# Generated by Django 3.2.6 on 2021-08-26 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdt', '0008_auto_20181128_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='paypalpdt',
            name='shipping_option_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=64, null=True),
        ),
        migrations.AddField(
            model_name='paypalpdt',
            name='shipping_option_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
